/* Generated by ts-generator ver. 0.0.8 */
/* tslint:disable */

import BN from "bn.js";
import { Contract, ContractOptions } from "web3-eth-contract";
import { EventLog } from "web3-core";
import { EventEmitter } from "events";
import { ContractEvent, Callback, TransactionObject, BlockType } from "./types";

interface EventOptions {
  filter?: object;
  fromBlock?: BlockType;
  topics?: string[];
}

export class TFCManager extends Contract {
  constructor(
    jsonInterface: any[],
    address?: string,
    options?: ContractOptions
  );
  clone(): TFCManager;
  methods: {
    claimTFC(
      amount: number | string,
      nonce: number | string,
      sig: string | number[]
    ): TransactionObject<void>;

    signer(): TransactionObject<string>;

    tfcToken(): TransactionObject<string>;

    usedNonces(arg0: number | string): TransactionObject<boolean>;
  };
  events: {
    ClaimTFC: ContractEvent<{
      recipient: string;
      amount: string;
      nonce: string;
      sig: string;
      0: string;
      1: string;
      2: string;
      3: string;
    }>;
    allEvents: (
      options?: EventOptions,
      cb?: Callback<EventLog>
    ) => EventEmitter;
  };
}
